global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pushgateway 监控
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  # 示例：Node Exporter（如果有的话）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 示例：自定义指标
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 5s
    metrics_path: /metrics

# 告警规则（可选）
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 示例告警规则
# rule_files:
#   - "alert_rules.yml"
